// This file was generated by tfxjs
const tfxjs = require("tfxjs");
const tfx = new tfxjs(
  ".",
  {}
);

tfx.plan("tfx Generated Plan", () => {
  
  tfx.module(
    "Teleport Deployment",
    'module.teleport_deployment',
    tfx.resource(
      "Urls",
      'ibm_appid_redirect_urls.urls',
      {
        "urls": [
          "https://at-teleport-vsi-0.null:3080/v1/webapi/oidc/callback"
        ]
      }
    ),
    tfx.resource(
      "Bucket",
      'ibm_cos_bucket.bucket',
      {
        "abort_incomplete_multipart_upload_days": [],
        "activity_tracking": [],
        "archive_rule": [],
        "bucket_name": "at-teleport-test",
        "endpoint_type": "public",
        "expire_rule": [],
        "force_delete": true,
        "metrics_monitoring": [],
        "noncurrent_version_expiration": [],
        "object_versioning": [],
        "region_location": "eu-de",
        "resource_instance_id": "crn:v1:bluemix:public:cloud-object-storage:global:a/cdefe6d99f7ea459aacb25775fb88a33:a805891e-eaf6-4752-900f-851b39f8a212::",
        "retention_rule": [],
        "storage_class": "standard"
      }
    ),
    tfx.resource(
      "Appid Key",
      'ibm_resource_key.appid_key',
      {
        "name": "at-teleport-app-id-key",
        "role": "Writer",
        "tags": [
          "tag1",
          "tag2"
        ]
      }
    ),
    tfx.resource(
      "Key",
      'ibm_resource_key.key',
      {
        "name": "at-teleport-test",
        "parameters": {
          "HMAC": "true"
        },
        "resource_instance_id": "crn:v1:bluemix:public:cloud-object-storage:global:a/cdefe6d99f7ea459aacb25775fb88a33:a805891e-eaf6-4752-900f-851b39f8a212::",
        "role": "Writer",
        "tags": [
          "tag1",
          "tag2"
        ]
      }
    ),
  );
  
  tfx.module(
    "Appid",
    'module.teleport_deployment.module.appid',
    tfx.resource(
      "Appid 0",
      'ibm_resource_instance.appid[0]',
      {
        "location": "eu-de",
        "name": "at-app-id",
        "plan": "graduated-tier",
        "resource_group_id": "1234",
        "service": "appid",
        "tags": [
          "tag1",
          "tag2"
        ]
      }
    ),
  );
  
  tfx.module(
    "Teleport Config",
    'module.teleport_deployment.module.teleport_config',
    tfx.resource(
      "Cloud Init",
      'template_cloudinit_config.cloud_init',
      {
        "base64_encode": false,
        "gzip": false,
        "part": [
          {
            "content_type": null,
            "filename": null,
            "merge_type": null
          }
        ]
      }
    ),
  );
  
  tfx.module(
    "Vsi Teleport 1",
    'module.teleport_deployment.module.teleport_vsi.module.vsi["teleport-1"]',
    tfx.resource(
      "Vsi",
      'ibm_is_instance.vsi',
      {
        "boot_volume": [
          {
            "snapshot": null
          }
        ],
        "force_action": false,
        "image": "r010-49cc5202-f4dd-44d6-ace4-89209588303a",
        "keys": [
          "sshkey123"
        ],
        "name": "at-teleport-1",
        "primary_network_interface": [
          {
            "allow_ip_spoofing": false,
            "subnet": "subnet-id-1234"
          }
        ],
        "profile": "cx2-4x8",
        "resource_group": "1234",
        "vpc": "vpc-123",
        "wait_before_delete": true,
        "zone": "eu-de-1"
      }
    ),
  );
});
